/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package student_signup_._login;

/**
 *
 * @author emman
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InsertTask_RightPanel = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        txtTaskName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        radNotIssued = new javax.swing.JRadioButton();
        radIssued = new javax.swing.JRadioButton();
        radInProcess = new javax.swing.JRadioButton();
        radVerifying = new javax.swing.JRadioButton();
        radCompleted = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        txtCategory = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnInsertTask = new javax.swing.JButton();
        btnClearAll = new javax.swing.JButton();
        HeaderPanel19 = new javax.swing.JPanel();
        lblHeaderText19 = new javax.swing.JLabel();
        DiplayData = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Task Name: ");

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Completion Status:");

        radNotIssued.setForeground(new java.awt.Color(204, 204, 204));
        radNotIssued.setText("Not Issued");

        radIssued.setForeground(new java.awt.Color(204, 204, 204));
        radIssued.setText("Issued");

        radInProcess.setForeground(new java.awt.Color(204, 204, 204));
        radInProcess.setText("In Process");

        radVerifying.setForeground(new java.awt.Color(204, 204, 204));
        radVerifying.setText("Verifying");

        radCompleted.setForeground(new java.awt.Color(204, 204, 204));
        radCompleted.setText("Completed");

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Description:");

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        jScrollPane1.setViewportView(txtDescription);

        jLabel4.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Category: ");

        btnInsertTask.setText("Insert Task");

        btnClearAll.setText("Clear All");

        InsertTask_RightPanel.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        InsertTask_RightPanel.setLayer(txtTaskName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        InsertTask_RightPanel.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        InsertTask_RightPanel.setLayer(radNotIssued, javax.swing.JLayeredPane.DEFAULT_LAYER);
        InsertTask_RightPanel.setLayer(radIssued, javax.swing.JLayeredPane.DEFAULT_LAYER);
        InsertTask_RightPanel.setLayer(radInProcess, javax.swing.JLayeredPane.DEFAULT_LAYER);
        InsertTask_RightPanel.setLayer(radVerifying, javax.swing.JLayeredPane.DEFAULT_LAYER);
        InsertTask_RightPanel.setLayer(radCompleted, javax.swing.JLayeredPane.DEFAULT_LAYER);
        InsertTask_RightPanel.setLayer(jSeparator2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        InsertTask_RightPanel.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        InsertTask_RightPanel.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        InsertTask_RightPanel.setLayer(txtCategory, javax.swing.JLayeredPane.DEFAULT_LAYER);
        InsertTask_RightPanel.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        InsertTask_RightPanel.setLayer(btnInsertTask, javax.swing.JLayeredPane.DEFAULT_LAYER);
        InsertTask_RightPanel.setLayer(btnClearAll, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout InsertTask_RightPanelLayout = new javax.swing.GroupLayout(InsertTask_RightPanel);
        InsertTask_RightPanel.setLayout(InsertTask_RightPanelLayout);
        InsertTask_RightPanelLayout.setHorizontalGroup(
            InsertTask_RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsertTask_RightPanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(InsertTask_RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(InsertTask_RightPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(41, 41, 41)
                        .addGroup(InsertTask_RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radNotIssued)
                            .addComponent(radIssued)
                            .addComponent(radInProcess)
                            .addComponent(radVerifying)
                            .addComponent(radCompleted)
                            .addComponent(txtTaskName, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(InsertTask_RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InsertTask_RightPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(InsertTask_RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(InsertTask_RightPanelLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(InsertTask_RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnClearAll, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(InsertTask_RightPanelLayout.createSequentialGroup()
                                        .addComponent(txtCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(btnInsertTask, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(InsertTask_RightPanelLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(351, Short.MAX_VALUE))
        );
        InsertTask_RightPanelLayout.setVerticalGroup(
            InsertTask_RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsertTask_RightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InsertTask_RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InsertTask_RightPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(InsertTask_RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(btnInsertTask))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClearAll))
                    .addGroup(InsertTask_RightPanelLayout.createSequentialGroup()
                        .addGroup(InsertTask_RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTaskName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(radNotIssued)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radIssued)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radInProcess)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radVerifying)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radCompleted))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        lblHeaderText19.setFont(new java.awt.Font("Bookman Old Style", 1, 25)); // NOI18N
        lblHeaderText19.setForeground(new java.awt.Color(204, 204, 204));
        lblHeaderText19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout HeaderPanel19Layout = new javax.swing.GroupLayout(HeaderPanel19);
        HeaderPanel19.setLayout(HeaderPanel19Layout);
        HeaderPanel19Layout.setHorizontalGroup(
            HeaderPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanel19Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblHeaderText19, javax.swing.GroupLayout.PREFERRED_SIZE, 1261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(269, Short.MAX_VALUE))
        );
        HeaderPanel19Layout.setVerticalGroup(
            HeaderPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanel19Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblHeaderText19, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(745, 745, 745))
        );

        javax.swing.GroupLayout DiplayDataLayout = new javax.swing.GroupLayout(DiplayData);
        DiplayData.setLayout(DiplayDataLayout);
        DiplayDataLayout.setHorizontalGroup(
            DiplayDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1082, Short.MAX_VALUE)
        );
        DiplayDataLayout.setVerticalGroup(
            DiplayDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 325, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HeaderPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InsertTask_RightPanel))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(DiplayData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HeaderPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(DiplayData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InsertTask_RightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DiplayData;
    private javax.swing.JPanel HeaderPanel19;
    private javax.swing.JLayeredPane InsertTask_RightPanel;
    private javax.swing.JButton btnClearAll;
    private javax.swing.JButton btnInsertTask;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblHeaderText19;
    private javax.swing.JRadioButton radCompleted;
    private javax.swing.JRadioButton radInProcess;
    private javax.swing.JRadioButton radIssued;
    private javax.swing.JRadioButton radNotIssued;
    private javax.swing.JRadioButton radVerifying;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtTaskName;
    // End of variables declaration//GEN-END:variables
}
